<?php
/*
 * function description - get list of all bugs from bugzilla
 *
 * returns -
 * either a error div or result generated by bugzilla
 * */
function getAllBugs() {
    require_once(ABSPATH.'wp-content/plugins/wp-bugzilla/endpoints/bugzilla-base-endpoint.php');
    $response = executeRestAPIWith('GET', '/rest.cgi/bug', null);
    $result = $response[0];
    $http_code = $response[1];
    $error = $response[2];

    if ($http_code == 0) {
        return ['Error', '<div><h1> Please specify the BASE URL in settings of "Bugzilla Integrator" plugin. </h1></div>'];
    } else if ($error || ($http_code != 200)) {
        return ['Error', '<div><h1> Something went wrong. <?php echo $error ?> </h1></div>'];
    } else {
        return ['Success', $result];
    }
}