<?php
/*
 * function description - authenticate bugzilla user with provided username/password
 * @params -
 * $username - bugzilla username
 * $password - bugzilla password
 *
 * returns -
 * either a error div or result generated by bugzilla
 * */
function authenticateUser($username, $password) {
    require_once('bugzilla-base-endpoint.php');
    $response = executeRestAPIWith('GET', '/rest.cgi/login?login='.$username.'&password='.$password, null);
    $result = $response[0];
    $http_code = $response[1];
    $error = $response[2];

    if ($http_code == 0) {
        return ['Error', '<div><h1> Please specify the BASE URL in settings of "Bugzilla Integrator" plugin. </h1></div>'];
    } else if ($error || ($http_code != 200)) {
        return ['Error', '<span class="wrap"><h1> Please enter valid username or password. </h1></span>'];
    } else {
        return ['Success', $result];
    }
}